---
- name: Deploying nop-commerce website
  hosts: all
  become: yes
  tasks:
    - name: Updating Repository urls
      apt:
        update_cache: yes
    - name: Downloading dependecies for .NET Application
      get_url:
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        dest: .
    - name: Installing dependecies for .NET Application
      apt:
        deb: ./packages-microsoft-prod.deb
    - name: Make sure HTTPS is supported by apt
      apt:
        name:
          - apt-transport-https
        update_cache: no
        state: present
    - name: Install .NET 
      apt:
        name:
          - aspnetcore-runtime-6.0
        update_cache: yes
        state: present
    - name: Installing nginx webserver
      apt:
        name: nginx
        state: present
    - name: configuring nginx as a reverse proxy to forward requests to your ASP.NET Core app
      template: 
        src: 'default.j2'
        dest: /etc/nginx/sites-available/default
    - name: Creating directiories for nop-commerce
      file:
        path: /var/www/nopCommerce450
        state: directory
    - name: Downloading nop-commerce
      get_url:
        url: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.50.2/nopCommerce_4.50.2_NoSource_linux_x64.zip
        dest: /var/www/nopCommerce450
    - name: Installing Unzip
      apt:
        name: unzip
        state: present
    - name: Unzipping nop-commerce
      unarchive:
        src: /var/www/nopCommerce450/nopCommerce_4.50.2_NoSource_linux_x64.zip
        remote_src: yes
        dest: /var/www/nopCommerce450
    - name: Creating directiories for bin
      file:
        path: /var/www/nopCommerce450/bin
        state: directory
    - name: Creating directiories for bin
      file:
        path: /var/www/nopCommerce450/logs
        state: directory
    - name: changing the group and owner of nop-commerce directory
      file:
        path: /var/www/nopCommerce450
        state: directory
        group: www-data
        owner: www-data
        recurse: yes
    - name: configuring nginx as a reverse proxy to forward requests to your ASP.NET Core app
      template: 
        src: 'nopCommerce450.service.j2'
        dest: /etc/systemd/system/nopCommerce450.service
    - name: Starting nginx webserver
      systemd:
        name: 'nginx.service'
        state: started
    - name: Starting nopCommerce450.service
      systemd:
        name: 'nopCommerce450.service'
        state: started
    - name: Starting nopCommerce450.service
      systemd:
        name: 'nopCommerce450.service'
        state: restarted