---
- name: Deploying nop-commerce website
  hosts: all
  become: yes
  vars:
    - installation_directory: /var/www/nopCommerce450
    - nop_service_directory: /etc/systemd/system
  tasks:
    - name: Updating Repository urls
      apt:
        update_cache: yes
    - name: Downloading dependecies for .NET Application
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        dest: .
    - name: Installing dependecies for .NET Application
      apt:
        deb: ./packages-microsoft-prod.deb
    - name: Make sure HTTPS is supported by apt
      apt:
        name:
          - apt-transport-https
          - aspnetcore-runtime-6.0
        update_cache: yes
        state: present
    - name: Installing nginx webserver
      apt:
        name: nginx
        state: present
    - name: configuring nginx as a reverse proxy to forward requests to your ASP.NET Core app
      ansible.builtin.template: 
        src: 'default.j2'
        dest: /etc/nginx/sites-available/default
    - name: Creating directiories for nop-commerce
      ansible.builtin.file:
        path: "{{installation_directory}}"
        state: directory
    - name: Downloading nop-commerce
      ansible.builtin.get_url:
        url: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.50.2/nopCommerce_4.50.2_NoSource_linux_x64.zip
        dest: "{{installation_directory}}"
    - name: Installing Unzip
      apt:
        name: unzip
        state: present
    - name: Unzipping nop-commerce
      ansible.builtin.unarchive:
        src: "{{installation_directory}}/nopCommerce_4.50.2_NoSource_linux_x64.zip"
        remote_src: yes
        dest: "{{installation_directory}}"
    - name: Creating directiories for bin
      ansible.builtin.file:
        path: "{{installation_directory}}/bin"
        state: directory
    - name: Creating directiories for bin
      ansible.builtin.file:
        path: "{{installation_directory}}/logs"
        state: directory
    - name: changing the group and owner of nop-commerce directory
      ansible.builtin.file:
        path: "{{installation_directory}}"
        state: directory
        group: www-data
        owner: www-data
        recurse: yes
    - name: configuring nginx as a reverse proxy to forward requests to your ASP.NET Core app
      ansible.builtin.template: 
        src: 'nopCommerce450.service.j2'
        dest: "{{nop_service_directory}}/nopCommerce450.service"
    - name: Starting nginx webserver
      ansible.builtin.systemd:
        name: 'nginx.service'
        state: started
    - name: Starting nopCommerce450.service
      ansible.builtin.systemd:
        name: 'nopCommerce450.service'
        state: started
    - name: Starting nopCommerce450.service
      ansible.builtin.systemd:
        name: 'nopCommerce450.service'
        state: restarted